### ISSUE TITLE
[FR] Add support for Claude (anthropic)

### ISSUE THREAD

**Issue by CapCap** [xhjkl/well#5]
Request: support claude (anthropic) in addition to chatGPT

I've been using `well` a bunch, really enjoying it- but given claudes context is > 6x (200k) what chatGPTs is (22k), would be interesting to test it out too. 

Would you welcome a PR for this?

**Comment by xhjkl** [comment]
Hi, Max! Glad you dropped by! Great to know you found the thing useful.

I was thinking about adding Claude too, but my own experience shows that OpenAI's models are better at reasoning and code understanding, even if some benchmarks online indicate the opposite. Given that, and because I wanted to focus on the simplicity of implementation before version one comes out, I'm not rushing it.

The main problem with Anthropic is that you cannot easily plug in their api instead of OpenAI's, as you do with ollama, because there are subtle differences in schema.

Also, the newest `gpt-4o` has a context window of 128k, so the gap is closing:
https://platform.openai.com/docs/models/gpt-4o

Having said all that, the PR you're describing will be more than welcome.

The implementation details are entirely up to you, but if I were to start adding Anthropic today, I'd do it like follows:
* in `src/env.rs`, tell if there is `ANTHROPIC_API_KEY` env available, which will take precedence over `OPENAI_API_KEY`,
* perhaps wrap the envs in a structure and add a field to it that will tell which api flavor we are using: OpenAI's or Anthropic's,
* add a type marker field to `src/openai.rs@Chat` to distinguish between the flavors,
* split `src/openai/schema.rs` into `src/openai/schema/{openai,anthropic,common}.rs`.

<details>
<summary>I imagine the overall approach as follows...</summary>

```

trait ChatFlavor {
    fn complete(&self) -> Result<ChatCompletion>;
}

struct OpenAI;
struct Anthropic;

impl ChatFlavor for OpenAI {
    fn complete(&self) -> Result<ChatCompletion> {
        ...
    }
}

impl ChatFlavor for Anthropic {
    fn complete(&self) -> Result<ChatCompletion> {
        ...
    }
}

struct Chat<Flavor: ChatFlavor> {
    flavor: Flavor,
}

impl<Any: ChatFlavor> Chat<Any> {
    fn new() -> Chat<OpenAI> {
        Chat { flavor: OpenAI }
    }

    fn new_anthropic_flavored() -> Chat<Anthropic> {
        Chat { flavor: Anthropic }
    }

    fn complete(&self) -> Result<ChatCompletion> {
        self.flavor.complete()
    }
}

```

</details>

Of course, this is a lot of work, so if you lose interest to adding Anthropic, please feel free to submit another feature request, I'd love to discuss that.

**Comment by xhjkl** [comment]
On the second thought, perhaps we could just move to [Stainless](https://www.stainlessapi.com)/[Fern](https://buildwithfern.com) once they get there.

**Comment by xhjkl** [comment]
I'm assuming this is not getting any updates. Feel free to reopen.
